use crate::{CaseType, Priority};

/// Values supplied by a caller when opening a support case.
///
/// Identity, timestamps, and initial status are generated by the domain model.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateSupportCaseCommand {
    pub case_type: CaseType,
    pub title: String,
    pub description: String,
    pub reporter_id: String,
    pub assignee_id: Option<String>,
    pub project_id: Option<String>,
    pub service: Option<String>,
    pub environment: Option<String>,
    pub priority: Priority,
}
